services:
  markserv:
    build: .
    ports:
      - "${PORT:-8080}:8080"
      - "${LIVERELOAD_PORT:-35729}:${LIVERELOAD_PORT:-35729}"
    volumes:
      - ${REPO_PATH:-.}:/var/www:ro
    restart: unless-stopped
    stop_grace_period: 1s
